services:
  - type: web
    name: bookmarkvault
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: false
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_NAME
        value: Bookmarkvault
      - key: FRONTEND_DIST_DIR
        value: /usr/local/share/frontend/dist
      - key: CORS_ORIGIN
        value: "*"
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
